-- 1.sal 2000 이상인 사람의 부서 정보
-- 오라클에서만 허용하는 방식
SELECT D.DEPTNO, D.DNAME, E.EMPNO,E.ENAME, E.SAL
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO AND E.SAL>2000;

-- 표준 방식 NATURAL
SELECT DEPTNO , D.DNAME, E.EMPNO, E.ENAME, E.SAL
FROM EMP E NATURAL JOIN  DEPT D
WHERE SAL > 2000;

-- 표준 방식  USING
SELECT DEPTNO , D.DNAME, E.EMPNO, E.ENAME, E.SAL
FROM EMP E JOIN DEPT D USING(DEPTNO)
WHERE SAL > 2000;

-- 표준 방식  ON(WHERE에 썼던 조건을 ON에다가 쓰기...)
SELECT D.DEPTNO , D.DNAME, E.EMPNO, E.ENAME, E.SAL
FROM EMP E JOIN DEPT D ON(E.DEPTNO = D.DEPTNO)
WHERE SAL > 2000;



-- outer
SELECT E1.EMPNO, E1.ENAME,E1.MGR,
E2.EMPNO AS MGR_EMPNO,
E2.ENAME AS MGR_NAME
FROM EMP E1, EMP E2
WHERE E1.MGR  = E2.EMPNO(+);

-- 표준 방식
SELECT E1.EMPNO, E1.ENAME,E1.MGR,
E2.EMPNO AS MGR_EMPNO,
E2.ENAME AS MGR_NAME
FROM EMP E1 LEFT OUTER JOIN EMP E2 ON(E1.MGR = E2.EMPNO);

SELECT E1.EMPNO, E1.ENAME,E1.MGR,
E2.EMPNO AS MGR_EMPNO,
E2.ENAME AS MGR_NAME
FROM EMP E1 FULL OUTER JOIN EMP E2 ON(E1.MGR = E2.EMPNO)
ORDER BY E1.EMPNO;










-- 2번
SELECT D.DEPTNO, D.DNAME,
TRUNC(AVG(SAL)) AS AVG_SAL,
MAX(SAL) AS MAX_SAL,
MIN(SAL) AS MIN_SAL,
COUNT(*) AS CNT
FROM DEPT D, EMP E
WHERE D.DEPTNO = E.DEPTNO
GROUP BY D.DEPTNO, D.DNAME;

SELECT D.DEPTNO, D.DNAME,
TRUNC(AVG(SAL)) AS AVG_SAL,
MAX(SAL) AS MAX_SAL,
MIN(SAL) AS MIN_SAL,
COUNT(*) AS CNT
FROM DEPT D JOIN EMP E ON(D.DEPTNO = E.DEPTNO)
GROUP BY D.DEPTNO, D.DNAME;





-3번
SELECT D.DEPTNO, D.DNAME, E.EMPNO,E.ENAME, E.JOB,E.SAL
FROM DEPT D, EMP E
WHERE D.DEPTNO = E.DEPTNO(+)
ORDER BY E.DEPTNO, E.ENAME;

SELECT D.DEPTNO, D.DNAME, E.EMPNO,E.ENAME, E.JOB,E.SAL
FROM DEPT D LEFT OUTER JOIN EMP E on(D.DEPTNO = E.DEPTNO)
--WHERE D.DEPTNO = E.DEPTNO(+)
ORDER BY E.DEPTNO, E.ENAME;








-- 표준 방식 등가조인
SELECT E.EMPNO, E.ENAME,E.JOB,E.MGR, E.HIREDATE, E.SAL, E.COMM, DEPTNO, D.DNAME,D.LOC
FROM EMP E NATURAL JOIN DEPT D;

-- 오라클 방식 등가조인
SELECT E.EMPNO, E.ENAME,E.JOB,E.MGR, E.HIREDATE, E.SAL, E.COMM, DEPTNO, D.DNAME,D.LOC
FROM EMP E , DEPT D
WHERE E.DEPTNO = D.DEPTNO;





SELECT * FROM EMP;
SELECT * FROM DEPT;



