-- 데이터 입력시 제약을 걸어서 무조건 입력받게 하기....
CREATE TABLE TABLE_NOTNULL (
    LOGIN_ID     VARCHAR2(20) NOT NULL,
    LOGIN_PWD    VARCHAR2(20) NOT NULL,
    TEL          VARCHAR2(20)
);

CREATE TABLE TABLE_NOTNULL02 (
    LOGIN_ID     VARCHAR2(20) CONSTRAINT TABLE_NOTNULL20_LOGIN_NOT_NULL NOT NULL,
    LOGIN_PWD    VARCHAR2(20) NOT NULL,
    TEL          VARCHAR2(20)
);

DESC TABLE_NOTNULL;

INSERT INTO TABLE_NOTNULL (LOGIN_ID,LOGIN_PWD,TEL)
VALUES ('TEST','1234','010-1111-2222');

INSERT INTO TABLE_NOTNULL (LOGIN_ID,LOGIN_PWD)
VALUES ('TEST2','5678');


UPDATE TABLE_NOTNULL
SET TEL = '010-1111-222';

ALTER TABLE TABLE_NOTNULL 
MODIFY (TEL NOT NULL);

SELECT * FROM TABLE_NOTNULL;

SELECT * FROM USER_CONSTRAINTS;

CREATE TABLE TABLE_UNIQUE (
    LOGIN_ID    VARCHAR2(20) UNIQUE,
    LOGIN_PWD   VARCHAR2(20) NOT NULL,
    TEL         VARCHAR2(20)
);
DROP TABLE TABLE_UNIQUE;
INSERT INTO TABLE_UNIQUE(LOGIN_ID,LOGIN_PWD,TEL)
VALUES (NULL,'1234','1111');

COMMIT;

DESC TABLE_UNIQUE;

SELECT * FROM TABLE_UNIQUE;


CREATE TABLE TABLE_PK (
    LOGIN_ID    VARCHAR2(20)    PRIMARY KEY,
    LOGIN_PWD   VARCHAR2(20)     NOT NULL,
    TEL         VARCHAR2(20)    
);

-- PRIMARY KEY를 제약 조건으로 걸면 UNIQUE, NOT NULL, INDEX도 설정 된다.
INSERT INTO TABLE_PK(LOGIN_ID,LOGIN_PWD,TEL)
VALUES ('JJANG051','1234','1111');

-- FOREIGN KEY  정규화
SELECT * FROM EMP;

INSERT INTO EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (9999,'HONG','CLERK','7788',TO_DATE('2023-02-28', 'YYYY/MM/DD'),1200, NULL, 50);

SELECT * FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN ('EMP','DEPT');

SELECT * FROM DEPT;

CREATE TABLE DEPT_FK (
    DEPTNO  NUMBER(2) CONSTRAINT DEPTFK_DEPTNO_PK PRIMARY KEY,
    DNAME VARCHAR2(20),
    LOC VARCHAR2(20)
);


CREATE TABLE EMP_FK  (
    EMPNO NUMBER(4) CONSTRAINT EMPFK_EMPNO_PK PRIMARY KEY,
    ENAME VARCHAR2(10),
    JOB VARCHAR2(10),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7,2),
    COMM NUMBER(7,2),
    DEPTNO NUMBER(2) CONSTRAINT EMPFK_DEPTNO_FK REFERENCES DEPT_FK (DEPTNO)
);

-- 비밀번호  8자리 입력 


INSERT INTO DEPT_FK VALUES (10,'AAA','DANGSAN');
INSERT INTO DEPT_FK VALUES (20,'BBB','ILSAN');
INSERT INTO EMP_FK VALUES (2222,'TEST_USER','TEST_JOB',NULL, TO_DATE('2023-02-28','YYYY-MM-DD'),
    3000,NULL,20
);

CREATE TABLE TABLE_CHECK(
    LOGIN_ID     VARCHAR2(20) CONSTRAINT TABLE_CHECK_LOGIN_PK PRIMARY KEY,
    LOGIN_PWD    VARCHAR2(20) CONSTRAINT TABLE_LOGINPWD_CH CHECK ( LENGTH(LOGIN_PWD) > 3 ),
    TEL          VARCHAR2(20)
);

INSERT INTO TABLE_CHECK VALUES ('TEST_ID','1234','1111-2222');



CREATE TABLE TABLE_DEFAULT(
    LOGIN_ID     VARCHAR2(20) CONSTRAINT TABLE_CHECK_LOGIN_PK02 PRIMARY KEY,
    LOGIN_PWD    VARCHAR2(20) CONSTRAINT TABLE_LOGINPWD_CH02 CHECK ( LENGTH(LOGIN_PWD) > 3 ),
    TEL          VARCHAR2(20),
    REGDATE      DATE DEFAULT SYSDATE
);
INSERT INTO TABLE_DEFAULT (LOGIN_ID,LOGIN_PWD,TEL) VALUES ('TEST_ID02','1234','1111-2222');
SELECT * FROM TABLE_DEFAULT;
-- 안이 벅힌다.



CREATE TABLE DEPT_CONST (
  DEPTNO NUMBER(2) CONSTRAINT DEPTCONST_DEPTNO_PK PRIMARY KEY,
  DNAME VARCHAR2(14) CONSTRAINT  DEPTCONST_DEPTNO_UNIQUE UNIQUE , 
  LOC VARCHAR2(20) CONSTRAINT  DEPTCONST_DEPTNO_NN NOT NULL 
);

CREATE TABLE DEPT_CONST02 (
  DEPTNO NUMBER(2)  PRIMARY KEY,
  DNAME VARCHAR2(14)  UNIQUE , 
  LOC VARCHAR2(20)  NOT NULL 
);


CREATE TABLE EMP_CONST(
    EMPNO       NUMBER(4)       CONSTRAINT EMPCONST_EMPNO_PK PRIMARY KEY,
    ENAME       VARCHAR2(10)    CONSTRAINT EMPCONST_ENAME_NN NOT NULL,
    JOB         VARCHAR2(9),
    TEL         VARCHAR2(20) CONSTRAINT EMPCONST_TEL_UNQ UNIQUE,
    HIREDATE    DATE    ,
    SAL         NUMBER(7) CONSTRAINT EMPCONST_SAL_CHK CHECK(SAL BETWEEN 1000 AND 9999),
    COMM        NUMBER(7) ,
    DEPTNO      NUMBER(2) CONSTRAINT EMPCONST_DEPTNO_FK REFERENCES DEPT_CONST (DEPTNO)
);










