CREATE TABLE EMP_DDL (
    EMPNO       NUMBER(4),
    ENAME       VARCHAR2(30),
    JOB         VARCHAR2(20),
    MGR         NUMBER(4),
    HIREDATE    DATE,
    SAL         NUMBER(10),
    COMM        NUMBER(10),
    DEPTNO      NUMBER(2)
);
DESC EMP_DDL;


CREATE TABLE DEPT_DDL
AS SELECT * FROM DEPT;

DESC DEPT_DDL;
SELECT * FROM DEPT_DDL;

CREATE TABLE EMP_DDL_30
AS SELECT * FROM EMP WHERE DEPTNO=30;

SELECT * FROM EMP_DDL_30;

-- EMPDEPT_DDL로 테이블 만들기 내용은 필요없음...
CREATE TABLE EMPDEPT_DDL 
AS
SELECT E.EMPNO, E.ENAME,E.JOB,E.MGR,E.HIREDATE,E.SAL,E.COMM,E.DEPTNO, D.DNAME,D.LOC
FROM EMP E,DEPT D
WHERE 1 = 0;

SELECT * FROM EMPDEPT_DDL;

-- 다른 테이블 복제하기 (DATA도 같이 복제)
CREATE TABLE EMP_ALTER
AS SELECT * FROM EMP;

SELECT * FROM EMP_ALTER;

DESC EMP_ALTER;

-- 테이블 변경 (컬럼 추가)
ALTER TABLE EMP_ALTER
ADD HP VARCHAR2(20);

-- 테이블 변경 (컬럼의 이름 변경)
ALTER TABLE EMP_ALTER
RENAME COLUMN HP TO TEL;

-- 테이블 변경 (컬럼삭제)
ALTER TABLE EMP_ALTER
DROP COLUMN HP;

-- 테이블 변경 (컬럼의 테이터 형식 변경)
ALTER TABLE EMP_ALTER
MODIFY EMPNO NUMBER(6);

-- 테이블 이름 변경
RENAME EMP_ALTER TO EMP_RENAME;

SELECT * FROM EMP_RENAME;

--테이블 안에 있는 DATA 삭제
TRUNCATE TABLE EMP_RENAME;

--TABLE 삭제
DROP TABLE EMP_RENAME;
DROP TABLE EMP_TEMP11;


SELECT * FROM RECYCLEBIN;



DESC EMP_RENAME;


---연습문제
CREATE TABLE RMP_HW (
    EMPNO       NUMBER(4),
    ENAME       VARCHAR(10),
    JOB         VARCHAR(9),
    MGR         VARCHAR(4),
    HIREDATE    DATE,
    SAL         NUMBER(7,2),
    COMM        NUMBER(7,2),
    DEPTNO      NUMBER(2)
);

RENAME RMP_HW TO EMP_HW;

ALTER TABLE EMP_HW
ADD BIGO VARCHAR2(20);

ALTER TABLE EMP_HW
MODIFY BIGO VARCHAR2(30);

ALTER TABLE EMP_HW
RENAME COLUMN BIGO TO REMARK;

INSERT INTO EMP_HW
SELECT EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,NULL
FROM EMP;

SELECT * FROM EMP_HW;

DROP TABLE EMP_HW;

FLASHBACK TABLE EMP_HW TO BEFORE DROP;



