-- 날짜 관련 함수들....
SELECT SYSDATE AS NOW ,
SYSDATE-1 AS YESTERDAY,
SYSDATE+1 AS YESTERDAY
FROM DUAL;

-- ADD_MONTHS
SELECT SYSDATE AS NOW,
ADD_MONTHS(SYSDATE,3) AS 삼개월뒤
FROM DUAL;

SELECT EMPNO,ENAME,HIREDATE,
ADD_MONTHS(HIREDATE,120) AS WORK10YEAR
FROM EMP;

--MONTHS_BETWEEN
SELECT EMPNO, ENAME,HIREDATE,SYSDATE,
MONTHS_BETWEEN(HIREDATE,SYSDATE) AS MONTH01,
MONTHS_BETWEEN(SYSDATE, HIREDATE) AS MONTH02,
TRUNC(MONTHS_BETWEEN(SYSDATE, HIREDATE)) AS MONTH03
FROM EMP;

--NEXT_DAY(),LAST_DAY()
SELECT SYSDATE, NEXT_DAY(SYSDATE,'일요일'),
LAST_DAY(SYSDATE)
FROM DUAL;

-- 형변환 함수  TO_CHAR(),TO_NUMBER(), TO_DATE()
SELECT TO_NUMBER('12345') FROM DUAL;

SELECT EMPNO,ENAME,EMPNO + '500' FROM EMP;

SELECT SYSDATE, TO_CHAR(SYSDATE,'YYYY-MM-DD HH:MI:SS') FROM DUAL;

SELECT SYSDATE, 
TO_CHAR(SYSDATE,'MM') AS MM ,
TO_CHAR(SYSDATE,'MON') AS MON,   --JAN
TO_CHAR(SYSDATE,'MONTH') AS MONTH, -- JANUARY
TO_CHAR(SYSDATE,'DDD') AS DD, -- 날짜를 숫자로 포맷
TO_CHAR(SYSDATE,'DY') AS DY, -- 날짜를 숫자로 포맷
TO_CHAR(SYSDATE,'DAY') AS DAY -- 날짜를 숫자로 포맷
FROM DUAL;

SELECT SYSDATE, 
TO_CHAR(SYSDATE,'MM') AS MM ,
TO_CHAR(SYSDATE,'MON','NLS_DATE_LANGUAGE = KOREAN') AS MON,   --KOR
TO_CHAR(SYSDATE,'MON','NLS_DATE_LANGUAGE = ENGLISH') AS MON,   --ENG
TO_CHAR(SYSDATE,'MON','NLS_DATE_LANGUAGE = JAPANESE') AS MON,   --ENG

TO_CHAR(SYSDATE,'MONTH','NLS_DATE_LANGUAGE = KOREAN') AS MONTH, -- JANUARY
TO_CHAR(SYSDATE,'MONTH','NLS_DATE_LANGUAGE = ENGLISH') AS MONTH, -- JANUARY
TO_CHAR(SYSDATE,'MONTH','NLS_DATE_LANGUAGE = JAPANESE') AS MONTH, -- JANUARY
TO_CHAR(SYSDATE,'DDD') AS DD, -- 날짜를 숫자로 포맷
TO_CHAR(SYSDATE,'DY') AS DY, -- 날짜를 숫자로 포맷
TO_CHAR(SYSDATE,'DAY') AS DAY, -- 날짜를 숫자로 포맷
TO_CHAR(SYSDATE,'DAY','NLS_DATE_LANGUAGE = JAPANESE') AS DAY -- 날짜를 숫자로 포맷
FROM DUAL;


SELECT SAL,
TO_CHAR(SAL,'$999,999') AS SAL_$,
TO_CHAR(SAL,'L999,999') AS SAL_L,
TO_CHAR(SAL,'999,999.00') AS SAL_01,
TO_CHAR(SAL,'000,999,999.00') AS SAL_01
FROM EMP;

SELECT 1300 - '1500',
'1300' + '1500' 
FROM DUAL;

SELECT 1300 - '1500',
'1,300' + '1,500' 
FROM DUAL;

SELECT TO_NUMBER('1,300','999,999') - TO_NUMBER('1,500','999,999')  FROM DUAL;

-- 날짜로 바꾸기
SELECT 
TO_DATE('2023-02-22','YYYY-MM-DD') AS DATE01,
TO_DATE('2023-02-22 11:10:00','YYYY-MM-DD HH24:MI:SS') AS DATE02
FROM DUAL;

SELECT * FROM EMP
WHERE HIREDATE > TO_DATE('1981/06/01','YYYY/MM/DD');

-- NULL 연산안됨.  IS NULL IS NOT NULL  NVL(COMM,0)
SELECT EMPNO, ENAME,SAL,COMM,
SAL+COMM,NVL(COMM,0),
SAL*12+NVL(COMM,0) AS ANNSAL
FROM EMP;

SELECT EMPNO, ENAME, NVL2(COMM,'O','X') AS COMM FROM EMP;

SELECT EMPNO, ENAME,SAL,COMM,
SAL+COMM,NVL(COMM,0),
NVL2(COMM,SAL*12+COMM,SAL*12) AS ANNSAL
FROM EMP;

-- DECODE  IF ELSE 
-- 보너스 차등 지급  MANAGER 10  SALESMAN 5 ANALYST 0 3% 인상  
SELECT EMPNO,ENAME,JOB,SAL,
DECODE(JOB,
       'MANAGER',SAL*1.1,
       'SALESMAN',SAL*1.05,
       'ANALYST',SAL,
       SAL*1.03  -- ELSE
) AS BONUS
FROM EMP;

-- 한국 사람
SELECT EMPNO,ENAME,JOB,SAL,
DECODE(JOB,
       'MANAGER','관리자',
       'PRESIDENT','최고 관리자',
       'ANALYST','분석가',
       'CLERK','사원',
       '영업사원'  -- ELSE
) AS BONUS
FROM EMP;

SELECT EMPNO,ENAME,JOB,SAL,
    CASE JOB
        WHEN 'MANAGER'  THEN SAL*1.1
        WHEN 'SALESMAN' THEN SAL*1.05
        WHEN 'ANALYST'  THEN SAL
        ELSE SAL*1.03
    END AS BONUS
FROM EMP;

SELECT EMPNO,ENAME,JOB,SAL,
    CASE 
        WHEN JOB = 'MANAGER'  THEN SAL*1.1
        WHEN JOB = 'SALESMAN' THEN SAL*1.05
        WHEN JOB = 'ANALYST'  THEN SAL
        ELSE SAL*1.03
    END AS BONUS
FROM EMP;


-- COMM이 NULL이면 해당사항 없음, COMM 0이면 보너스 없음  COMM 이 있으면 BONUS : 300


SELECT EMPNO,ENAME,COMM,
    CASE 
        WHEN COMM       IS NULL THEN '해당사항 없음'
        WHEN COMM = 0           THEN '보너스'     
        WHEN COMM > 0           THEN '보너스 : ' || COMM
    END AS BONUS
FROM EMP;

-- SAL  2900 DIAMOND   2700 GOLD 2000 SILVER BRONZE
SELECT EMPNO,ENAME,SAL,
    CASE 
        WHEN SAL >= 2900        THEN 'DIAMOND'
        WHEN SAL >= 2700        THEN 'GOLD'     
        WHEN SAL >= 2000        THEN 'SILVER'
        ELSE 'BRONZE'
    END AS GRADE
FROM EMP;

SELECT ENAME, HIREDATE, TO_CHAR(HIREDATE,'Q') FROM EMP;   
--1분기 입사 2분기 입사 3분기 입사 4분기 입사


SELECT EMPNO, ENAME, 
    CASE 
        WHEN TO_CHAR(HIREDATE, 'Q') = '1' THEN '1분기 입사'
        WHEN TO_CHAR(HIREDATE, 'Q') = '2' THEN '2분기 입사'
        WHEN TO_CHAR(HIREDATE, 'Q') = '3' THEN '3분기 입사'
        WHEN TO_CHAR(HIREDATE, 'Q') = '4' THEN '4분기 입사'
        ELSE '해당사항 없음'
    END AS 분기별_입사
FROM EMP;




