-- 오라클에서 제공하는 기본 함수  이름()

-- 대소문자 치환
SELECT ENAME,LOWER(ENAME),UPPER(ENAME), INITCAP(ENAME) FROM EMP;

-- 길이 구하는 함수
SELECT ENAME, LENGTH(ENAME) FROM EMP;

SELECT ENAME FROM EMP
WHERE LENGTH(ENAME) = 6;

-- LENGTHB()는 바이트 수 돌려받음  한글은 3바이트
SELECT LENGTH('오라클'), LENGTHB('오라클 SQL') FROM DUAL;

--글자 잘라내기...
SELECT JOB,SUBSTR(JOB,1,2),SUBSTR(JOB,3,2),SUBSTR(JOB,5) FROM EMP;

--글자 잘라내기...
SELECT JOB,SUBSTR(JOB,-3,2),SUBSTR(JOB,-3) FROM EMP;

-- 문자열의 위치를 찾는 함수 INSTR
SELECT INSTR('HELLO, ORACLE','L',-1)  FROM DUAL;

SELECT INSTR(UPPER('Oracle database 11g release'),'DATABASE') AS RESULT FROM DUAL;

SELECT * FROM EMP
WHERE ENAME LIKE '%S%';

SELECT * FROM EMP
WHERE INSTR(ENAME,'S') > 0;

-- REPLACE  
SELECT '010-1111-2222' AS ORIGINAL, 
REPLACE('010-1111-2222','-',' ') AS BLANK,
REPLACE('010-1111-2222','-') AS BLANK02 FROM DUAL;


SELECT '010 1111-2222' AS Original,
REPLACE(REPLACE('010 1111-2222','-'),' ') AS NEW
FROM  DUAL;

-- RPAD VS LPAD

SELECT 'ORACLE', 
LPAD('ORACLE',10,'#') AS LPAD01,
RPAD('ORACLE',10,'#') AS RPAD01,
LPAD('ORACLE',10) AS LPAD01,
RPAD('ORACLE',10) AS RPAD01
FROM DUAL;

SELECT 
RPAD('971122-',14,'*') AS JUMIN,
RPAD('010-1111-',13,'*') AS PHONE
FROM DUAL;


-- EMP 에 이름을 처음 두글자만 남기고 마스킹 하기  SM***
SELECT  RPAD(SUBSTR(ENAME,1,2),LENGTH(ENAME),'*') FROM EMP;

-- 문자열 합치기....
SELECT  CONCAT(EMPNO, ENAME), CONCAT(EMPNO, CONCAT( '/', ENAME)) AS NEW FROM EMP;  
SELECT  ENAME || JOB, ENAME || '/' || JOB FROM EMP;  

-- 문자열 제거 --
SELECT  '   ORACLE   ' AS ORIGINAL ,
LTRIM('   ORACLE   ') AS LTRIM,
RTRIM('   ORACLE   ') AS RTRIM,
TRIM('   ORACLE   ') AS TRIM
FROM DUAL;

SELECT RTRIM('1234000','0') FROM DUAL;


-- 숫자 관련 함수
SELECT ROUND(1234.543) ,
ROUND(1234.443) ,
ROUND(1234.443,0)
FROM DUAL;

SELECT ROUND(1234.543,1) ,
ROUND(1234.447,2) ,
ROUND(1234.443,3)
FROM DUAL;


-- 절사  
SELECT 
TRUNC(1234.543) AS TRUNC,
TRUNC(1234.543,0) AS TRUNC0,
TRUNC(1234.543,1) AS TRUNC1,
TRUNC(1234.543,2) AS TRUNC2
FROM DUAL;

SELECT 
CEIL(3.14) ,
FLOOR(3.14)

FROM DUAL;









