--  기존 테이블 쓰지 않고 새로운 테이블 만들어서 넣기...

CREATE TABLE DEPT_TEMP
 AS SELECT * FROM DEPT;
SELECT * FROM DEPT_TEMP;

-- EMP 테이블 데이터를 그대로 들고와서 TABLE만들기 EMP_TEMP10
CREATE TABLE EMP_TEMP10 
AS SELECT * FROM EMP;

SELECT * FROM EMP_TEMP10;


-- INSERT

INSERT INTO DEPT_TEMP (DEPTNO, DNAME,LOC) VALUES (50,'DATABASE','SEOUL');
SELECT * FROM DEPT_TEMP;

INSERT INTO DEPT_TEMP (DEPTNO, DNAME,LOC) VALUES (70,'NETWORK',NULL);

CREATE TABLE EMP_TEMP
 AS SELECT * FROM EMP WHERE 1 = 0;
 SELECT * FROM EMP_TEMP;
 
 INSERT INTO EMP_TEMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
 VALUES (9999,'홍길동','PRESIDENT',NULL,'2023/02/27',5000,1000,10);
 
 INSERT INTO EMP_TEMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
 VALUES (9999,'이몽룡','PRESIDENT',NULL,'2023-02-27',5000,1000,10);
 
 INSERT INTO EMP_TEMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
 VALUES (9999,'전우치','PRESIDENT',NULL,TO_DATE('27/02/2023','DD/MM/YYYY'),5000,1000,10);
 
 INSERT INTO EMP_TEMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
 VALUES (9999,'임꺽정','PRESIDENT',NULL,SYSDATE,5000,1000,10);
 
 
 INSERT INTO EMP_TEMP 
 VALUES (8888,'성춘향','PRESIDENT',NULL,SYSDATE,5000,1000,10);
 
 INSERT INTO EMP_TEMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
 VALUES ((SELECT MAX(EMPNO) - 10 FROM EMP_TEMP),'성춘향','PRESIDENT',NULL,SYSDATE,5000,1000,10);
 
 SELECT MAX(EMPNO) + 1 FROM EMP_TEMP;
 
 SELECT * FROM EMP_TEMP;
 
 









