CREATE TABLE TEMP (
    COL01 VARCHAR2(20),
    COL02 VARCHAR2(20)
);

GRANT INSERT ON TEMP TO ORCLSTUDY;
GRANT SELECT ON TEMP TO ORCLSTUDY;
GRANT INSERT,SELECT,DELETE,UPDATE ON TEMP TO ORCLSTUDY;
REVOKE INSERT,SELECT,DELETE,UPDATE ON TEMP FROM ORCLSTUDY;

