--
SELECT * FROM EMP;

-- 이름이 JONES보다 월급 많이 받는 사람 알고 싶다.
SELECT SAL FROM EMP
WHERE ENAME = 'JONES';

SELECT * FROM EMP
WHERE SAL > 2975;


-- QUERY안에 QUERY 또 쓰기...
SELECT * FROM EMP
WHERE SAL > (SELECT SAL FROM EMP
WHERE ENAME = 'JONES');

--JONES보다 입사일이 빠른 사람...
SELECT * FROM EMP
WHERE HIREDATE < (SELECT HIREDATE FROM EMP
WHERE ENAME = 'JONES');


-- 이름이 ALLEN인 사원의 추가수당보다 더 많은 추가 수당을 받는 사람 구해 보기...
SELECT COMM FROM EMP
WHERE ENAME = 'ALLEN';

SELECT * FROM EMP 
WHERE COMM > (SELECT COMM FROM EMP
WHERE ENAME = 'ALLEN');

-- 20번 부서에 속한 사원 중 전체 사원의 평균 급여보다 많은 급여를 받는 사원 정보 뽑아보기....

--SELECT AVG(SAL) FROM EMP;
SELECT E.EMPNO,E.ENAME, E.JOB, E.SAL, D.DEPTNO, D.DNAME, D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO 
      AND D.DEPTNO = 20
      AND E.SAL > (SELECT AVG(SAL) FROM EMP);

-- DEPTNO 20, 30 부서 정보 다 뽑아 보기...
SELECT * FROM EMP
WHERE DEPTNO IN (20,30);

-- 각 부서별 최고 급여를 받는 사람과 동일한 급여를 받는 사람 출력 해보기...
SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO;

SELECT * FROM EMP
WHERE SAL IN (2850,3000,5000);

SELECT * FROM EMP
WHERE SAL IN (SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO);  --같은 경우

SELECT * FROM EMP
WHERE SAL <> ANY (SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO);

SELECT * FROM EMP
WHERE SAL > ALL (1000,2000,3000); -- 3000보다 큰 경우

SELECT * FROM EMP
WHERE SAL <> ALL (SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO); -- 3000보다 큰 경우



--EXISTS
SELECT * FROM EMP
WHERE EXISTS (SELECT DNAME FROM DEPT WHERE DEPTNO  = 100);  -- 있거나 없거나...

SELECT E.JOB, E.EMPNO, E.ENAME, E.SAL, E.DEPTNO, D.DNAME
  FROM EMP E, DEPT D
 WHERE E.DEPTNO = D.DEPTNO
   AND JOB = (SELECT JOB
                FROM EMP
               WHERE ENAME = 'ALLEN'); 


--CH91 연습 문제 1번
SELECT JOB FROM EMP
WHERE ENAME='ALLEN';

SELECT E.JOB ,E.EMPNO, E.ENAME,E.SAL, D.DEPTNO, D.DNAME
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND JOB = (SELECT JOB FROM EMP
WHERE ENAME='ALLEN') ;



--CH91 연습 문제 2번
--SELECT AVG(SAL) FROM EMP;
SELECT E.EMPNO, E.ENAME,D.DNAME,E.HIREDATE,D.LOC,E.SAL, S.GRADE
FROM EMP E, DEPT D, SALGRADE S
WHERE E.DEPTNO = D.DEPTNO 
AND E.SAL BETWEEN S.LOSAL AND S.HISAL 
AND E.SAL > (SELECT AVG(SAL) FROM EMP)
ORDER BY E.SAL DESC;


-- CH09 연슴문제3번
SELECT E.EMPNO,E.ENAME,E.JOB,E.DEPTNO,D.DNAME,D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND E.DEPTNO = 10 
AND JOB NOT IN(SELECT JOB FROM EMP WHERE DEPTNO = 30);




