CREATE USER ORCLSTUDY
IDENTIFIED BY ORACLE;

CREATE USER ORCLSTUDY02
IDENTIFIED BY ORACLE;

-- CONNECT 는 ROLE (CREATE SESSION, CREATE TABLE)
-- RESOURCE는 ROLE (CREATE SESSION, CREATE TABLE)
GRANT CONNECT, RESOURCE TO ORCLSTUDY02;

-- 접속 권한 부여
GRANT CREATE SESSION, RESOURCE, 
CREATE TABLE TO ORCLSTUDY;

REVOKE RESOURCE, CREATE TABLE FROM ORCLSTUDY02;

DROP USER ORCLSTUDY02 CASCADE;


-- ROLE 만들기.....
CREATE ROLE ROLESTUDY;
GRANT CONNECT,RESOURCE,CREATE VIEW, CREATE SYNONYM TO ROLESTUDY;

GRANT ROLESTUDY TO ORCLSTUDY02;



CREATE USER TISJJANG051
IDENTIFIED BY 1234;



